-- 우리 반에 AI가 숨어있다
-- Supabase SQL Editor에서 전체를 한 번에 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text unique not null check (code ~ '^[0-9]{4}$'),
  host_key text not null,
  topic text not null default '요즘 내가 가장 재미있게 하는 것은?',
  duration_sec integer not null default 300 check (duration_sec between 60 and 900),
  difficulty text not null default 'normal' check (difficulty in ('easy','normal','hard')),
  status text not null default 'lobby' check (status in ('lobby','chat','vote','reveal','closed')),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  ends_at timestamptz,
  last_ai_at timestamptz
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  participant_key text not null,
  nickname text not null,
  emoji text not null,
  is_ai boolean not null default false,
  joined_at timestamptz not null default now(),
  unique(room_id, participant_key),
  unique(room_id, nickname)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  participant_id uuid not null references public.participants(id) on delete cascade,
  nickname text not null,
  emoji text not null,
  body text not null check (char_length(body) between 1 and 120),
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  voter_participant_id uuid not null references public.participants(id) on delete cascade,
  target_participant_id uuid not null references public.participants(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(room_id, voter_participant_id)
);

create index if not exists messages_room_id_id_idx on public.messages(room_id,id);
create index if not exists participants_room_id_idx on public.participants(room_id);
create index if not exists votes_room_id_idx on public.votes(room_id);

alter table public.rooms enable row level security;
alter table public.participants enable row level security;
alter table public.messages enable row level security;
alter table public.votes enable row level security;

-- 브라우저에는 테이블 직접 조회 권한을 주지 않습니다.
-- 모든 읽기/쓰기는 방 코드 범위의 SECURITY DEFINER RPC를 통해 수행합니다.
revoke all on public.rooms from anon;
revoke all on public.participants from anon;
revoke all on public.messages from anon;
revoke all on public.votes from anon;

create or replace function public._room_by_code(p_code text)
returns uuid
language sql stable security definer set search_path=public
as $$ select id from rooms where code=p_code limit 1 $$;

create or replace function public._random_alias(p_room_id uuid)
returns table(nickname text, emoji text)
language plpgsql volatile security definer set search_path=public
as $$
declare
  animals text[] := array['토끼','호랑이','펭귄','여우','곰','수달','고양이','강아지','판다','햄스터','다람쥐','부엉이','사슴','오리','코알라','물개','치타','너구리','알파카','돌고래'];
  emojis text[]  := array['🐰','🐯','🐧','🦊','🐻','🦦','🐱','🐶','🐼','🐹','🐿️','🦉','🦌','🦆','🐨','🦭','🐆','🦝','🦙','🐬'];
  i int; n int; candidate text;
begin
  for tries in 1..80 loop
    i := 1 + floor(random()*array_length(animals,1))::int;
    n := 10 + floor(random()*90)::int;
    candidate := animals[i] || n::text;
    if not exists(select 1 from participants where room_id=p_room_id and participants.nickname=candidate) then
      nickname := candidate; emoji := emojis[i]; return next; return;
    end if;
  end loop;
  nickname := '참가자' || floor(random()*9000+1000)::int::text;
  emoji := '🙂';
  return next;
end $$;

create or replace function public.create_room(
  p_topic text,
  p_duration_sec integer,
  p_difficulty text,
  p_host_key text
)
returns table(room_id uuid, code text, topic text)
language plpgsql security definer set search_path=public
as $$
declare v_code text; v_id uuid;
begin
  if char_length(coalesce(p_host_key,'')) < 20 then raise exception 'INVALID_HOST_KEY'; end if;
  if p_difficulty not in ('easy','normal','hard') then raise exception 'INVALID_DIFFICULTY'; end if;
  p_duration_sec := greatest(60,least(coalesce(p_duration_sec,300),900));
  for tries in 1..50 loop
    v_code := lpad((floor(random()*10000))::int::text,4,'0');
    begin
      insert into rooms(code,host_key,topic,duration_sec,difficulty)
      values(v_code,p_host_key,left(coalesce(nullif(trim(p_topic),''),'자유롭게 이야기해 봅시다.'),80),p_duration_sec,p_difficulty)
      returning id into v_id;
      room_id:=v_id; code:=v_code;
      select r.topic into topic from rooms r where r.id=v_id;
      return next; return;
    exception when unique_violation then null;
    end;
  end loop;
  raise exception 'ROOM_CODE_FAILED';
end $$;

create or replace function public.get_room_public(p_code text)
returns table(
  room_id uuid, code text, topic text, duration_sec integer, difficulty text,
  status text, started_at timestamptz, ends_at timestamptz,
  ai_participant_id uuid, ai_nickname text, ai_emoji text
)
language sql stable security definer set search_path=public
as $$
  select r.id,r.code,r.topic,r.duration_sec,r.difficulty,r.status,r.started_at,r.ends_at,
    case when r.status='reveal' then a.id else null end,
    case when r.status='reveal' then a.nickname else null end,
    case when r.status='reveal' then a.emoji else null end
  from rooms r
  left join participants a on a.room_id=r.id and a.is_ai=true
  where r.code=p_code
  limit 1
$$;

create or replace function public.join_room(p_code text,p_participant_key text)
returns table(room_id uuid,participant_id uuid,nickname text,emoji text,has_voted boolean)
language plpgsql security definer set search_path=public
as $$
declare r rooms%rowtype; p participants%rowtype; a record;
begin
  select * into r from rooms where code=p_code limit 1;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;

  select * into p from participants where participants.room_id=r.id and participant_key=p_participant_key and is_ai=false limit 1;
  if found then
    room_id:=r.id; participant_id:=p.id; nickname:=p.nickname; emoji:=p.emoji;
    has_voted:=exists(select 1 from votes where votes.room_id=r.id and voter_participant_id=p.id);
    return next; return;
  end if;

  if r.status<>'lobby' then raise exception 'ROOM_ALREADY_STARTED'; end if;
  if (select count(*) from participants where participants.room_id=r.id and is_ai=false)>=30 then raise exception 'ROOM_FULL'; end if;
  if char_length(coalesce(p_participant_key,''))<20 then raise exception 'INVALID_PARTICIPANT_KEY'; end if;

  select * into a from _random_alias(r.id);
  insert into participants(room_id,participant_key,nickname,emoji,is_ai)
  values(r.id,p_participant_key,a.nickname,a.emoji,false)
  returning * into p;

  room_id:=r.id; participant_id:=p.id; nickname:=p.nickname; emoji:=p.emoji; has_voted:=false;
  return next;
end $$;

create or replace function public.list_participants(p_code text)
returns table(participant_id uuid,nickname text,emoji text,revealed_as_ai boolean)
language sql stable security definer set search_path=public
as $$
  select p.id,p.nickname,p.emoji,
    case when r.status='reveal' then p.is_ai else false end
  from rooms r join participants p on p.room_id=r.id
  where r.code=p_code
  order by p.joined_at,p.nickname
$$;

create or replace function public.get_messages(p_code text)
returns table(id bigint,room_id uuid,participant_id uuid,nickname text,emoji text,body text,created_at timestamptz)
language sql stable security definer set search_path=public
as $$
  select m.id,m.room_id,m.participant_id,m.nickname,m.emoji,m.body,m.created_at
  from rooms r join messages m on m.room_id=r.id
  where r.code=p_code
  order by m.id asc
  limit 300
$$;

create or replace function public.host_start_room(p_code text,p_host_key text)
returns void
language plpgsql security definer set search_path=public
as $$
declare r rooms%rowtype; a record;
begin
  select * into r from rooms where code=p_code and host_key=p_host_key for update;
  if not found then raise exception 'HOST_AUTH_FAILED'; end if;
  if r.status<>'lobby' then raise exception 'INVALID_STATUS'; end if;
  if (select count(*) from participants where room_id=r.id and is_ai=false)<2 then raise exception 'NEED_AT_LEAST_2_STUDENTS'; end if;

  if not exists(select 1 from participants where room_id=r.id and is_ai=true) then
    select * into a from _random_alias(r.id);
    insert into participants(room_id,participant_key,nickname,emoji,is_ai)
    values(r.id,'AI-'||encode(gen_random_bytes(20),'hex'),a.nickname,a.emoji,true);
  end if;
  update rooms set status='chat',started_at=now(),ends_at=now()+make_interval(secs=>duration_sec) where id=r.id;
end $$;

create or replace function public.send_message(p_code text,p_participant_key text,p_body text)
returns bigint
language plpgsql security definer set search_path=public
as $$
declare r rooms%rowtype; p participants%rowtype; msg text; new_id bigint;
begin
  select * into r from rooms where code=p_code limit 1;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if r.status<>'chat' or (r.ends_at is not null and now()>r.ends_at+interval '5 seconds') then raise exception 'ROOM_CLOSED'; end if;
  select * into p from participants where room_id=r.id and participant_key=p_participant_key and is_ai=false limit 1;
  if not found then raise exception 'PARTICIPANT_AUTH_FAILED'; end if;
  msg:=trim(coalesce(p_body,''));
  if char_length(msg)<1 or char_length(msg)>120 then raise exception 'INVALID_MESSAGE'; end if;

  -- 전화번호, 이메일, URL 등 명백한 개인정보/외부연결 패턴 차단
  if msg ~* '([0-9]{2,3}[- ]?[0-9]{3,4}[- ]?[0-9]{4})|([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})|(https?://|www\.)'
  then raise exception 'PERSONAL_INFO_BLOCKED'; end if;

  insert into messages(room_id,participant_id,nickname,emoji,body)
  values(r.id,p.id,p.nickname,p.emoji,msg) returning id into new_id;
  return new_id;
end $$;

create or replace function public.host_begin_vote(p_code text,p_host_key text)
returns void
language plpgsql security definer set search_path=public
as $$
declare r rooms%rowtype;
begin
  select * into r from rooms where code=p_code and host_key=p_host_key for update;
  if not found then raise exception 'HOST_AUTH_FAILED'; end if;
  if r.status not in ('chat','vote') then raise exception 'INVALID_STATUS'; end if;
  update rooms set status='vote' where id=r.id;
end $$;

create or replace function public.submit_vote(p_code text,p_participant_key text,p_target_id uuid)
returns void
language plpgsql security definer set search_path=public
as $$
declare r rooms%rowtype; voter participants%rowtype; target participants%rowtype;
begin
  select * into r from rooms where code=p_code limit 1;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if r.status<>'vote' then raise exception 'INVALID_STATUS'; end if;
  select * into voter from participants where room_id=r.id and participant_key=p_participant_key and is_ai=false limit 1;
  if not found then raise exception 'PARTICIPANT_AUTH_FAILED'; end if;
  select * into target from participants where id=p_target_id and room_id=r.id limit 1;
  if not found or target.id=voter.id then raise exception 'INVALID_VOTE'; end if;
  insert into votes(room_id,voter_participant_id,target_participant_id)
  values(r.id,voter.id,target.id)
  on conflict(room_id,voter_participant_id) do update set target_participant_id=excluded.target_participant_id,created_at=now();
end $$;

create or replace function public.host_get_results(p_code text,p_host_key text)
returns table(participant_id uuid,nickname text,emoji text,vote_count bigint,total_votes bigint,total_humans bigint)
language plpgsql stable security definer set search_path=public
as $$
declare rid uuid;
begin
  select id into rid from rooms where code=p_code and host_key=p_host_key;
  if rid is null then raise exception 'HOST_AUTH_FAILED'; end if;
  return query
  select p.id,p.nickname,p.emoji,count(v.id),
    (select count(*) from votes where room_id=rid),
    (select count(*) from participants where room_id=rid and is_ai=false)
  from participants p
  left join votes v on v.target_participant_id=p.id and v.room_id=rid
  where p.room_id=rid
  group by p.id,p.nickname,p.emoji,p.joined_at
  order by count(v.id) desc,p.joined_at;
end $$;

create or replace function public.host_reveal(p_code text,p_host_key text)
returns void
language plpgsql security definer set search_path=public
as $$
declare rid uuid;
begin
  select id into rid from rooms where code=p_code and host_key=p_host_key for update;
  if rid is null then raise exception 'HOST_AUTH_FAILED'; end if;
  update rooms set status='reveal' where id=rid and status in ('vote','reveal');
end $$;

create or replace function public.get_public_results(p_code text)
returns table(participant_id uuid,nickname text,emoji text,vote_count bigint)
language plpgsql stable security definer set search_path=public
as $$
declare rid uuid; st text;
begin
  select id,status into rid,st from rooms where code=p_code;
  if rid is null then raise exception 'ROOM_NOT_FOUND'; end if;
  if st<>'reveal' then raise exception 'NOT_REVEALED'; end if;
  return query
  select p.id,p.nickname,p.emoji,count(v.id)
  from participants p
  left join votes v on v.target_participant_id=p.id and v.room_id=rid
  where p.room_id=rid
  group by p.id,p.nickname,p.emoji,p.joined_at
  order by count(v.id) desc,p.joined_at;
end $$;

grant execute on function public.create_room(text,integer,text,text) to anon;
grant execute on function public.get_room_public(text) to anon;
grant execute on function public.join_room(text,text) to anon;
grant execute on function public.list_participants(text) to anon;
grant execute on function public.get_messages(text) to anon;
grant execute on function public.host_start_room(text,text) to anon;
grant execute on function public.send_message(text,text,text) to anon;
grant execute on function public.host_begin_vote(text,text) to anon;
grant execute on function public.submit_vote(text,text,uuid) to anon;
grant execute on function public.host_get_results(text,text) to anon;
grant execute on function public.host_reveal(text,text) to anon;
grant execute on function public.get_public_results(text) to anon;

-- 오래된 게임을 수동 정리할 때:
-- delete from public.rooms where created_at < now() - interval '7 days';
